theme: jekyll-theme-minimal
title: Khoi Huynh's homepage
description: A clean and modern developer portfolio showcasing my projects, skills, and experience in bioinformatics, web development, open-source contributions, and software engineering.
